# Generated by Django 5.2.8 on 2025-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefile',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicefile',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicefile',
            name='total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
