# Generated by Django 5.2.8 on 2025-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('demo', 'Demo'), ('starter', 'Starter'), ('advanced', 'Advanced'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uploads_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
